name: Linter
on:
  pull_request: ~
  push:
    branches:
      - '*'

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nebularg/actions-luacheck@v1
        with:
          files: 'lua'
